### ISSUE TITLE
Load variants from variant_identity table and pass through normalizer

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/clinvar-gk-pilot#1]
We are initially creating files to feed the clinvar-gk-pilot transformation in BQ and storing them in GCS. The contextual variations will be contained in the "variation_identity" files using the variation_identity_v2 bq procedure in the clingen-stage BW project procedures (If you cannot find/see this proc you may need to be added to the proper google group that has permissions to share project-level procedures).

Using the variation_identity GCS file format read and generate VRSified output using the normalizer API (or the direct VRS-Python api if more performant and capable).

This is a very basic step to starting the development of the full SCV variant pathogenicity statement output that the GK-Pilot v2 is aiming to deliver in the ver near term.

**Comment by larrybabb** [comment]
@toneillbroad I believe @theferrit32 has finished this mvp task. if you think so based on the handoff he's made to you, please close this. If not please update what is left to assure this is working and prioritize accordingly.
