### ISSUE TITLE
Switch SPDI endpoint from to_canonical_variation to translate_from

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/clinvar-gk-pilot#2]
Depends on https://github.com/clingen-data-model/architecture/issues/567

Originally we were depending on the "to_canonical_variation" to get the SPDI - based transform of the VRS variation. Since we are moving away from the "CanonicalVariation" form in VRS 1.x we no longer need this. A much more streamlined approach is to switch to use the "translate_from" api on the normalizer service.

**Comment by larrybabb** [comment]
@toneillbroad I believe @theferrit32 has already completed this task as well. If you can verify then please close this.
