### ISSUE TITLE
Send final gnomad gks cohortAlleleFrequency schema to browser team

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clinvar-gk-pilot#33]
Matt S is expecting us to send him the final version of the CohortAlleleFrequency schema for gnomad v4 so that he can begin integrating it into the graphQL API.  

There is some urgency to this since it is preventing them from even starting their analysis and work.

The expectation is that we will be testing the results of their work and that the graphQL API will only support querying a single variant at a time.

**Comment by theferrit32** [comment]
done
