### ISSUE TITLE
Use vrs_xform_plan to determine how to normalize variant

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/clinvar-gk-pilot#7]
Code the Variation normalization routine to rely solely on the vrs_xform_plan within the data feed versus coding logic to determine which api to call based on the various data attributes.  The upstream data feed will take sole responsibility for determining what data and api will be used to vrsify the variations.

**Comment by theferrit32** [comment]
Discussed on 2/15/2024 as a high priority item to implement for GA4GH April workshops

- we need a way to create the variation_identity data without needing @larrybabb to push a button
- determine which vrs python translator (or model) methods support which clinvar variation cases

**Comment by toneillbroad** [comment]
For discussion on how to implement this ticket:
```
vrs_xform_plan.type
- 		Allele
- 		CopyNumberChange
- 		CopyNumberCount
- 		Unsupported

vrs_xform_plan.policy
- 		Absolute copy count
- 		Canonical SPDI
- 		Copy number change (cn loss|del and cn gain|dup)
- 		Genotype/Haplotype
- 		Invalid/unsupported hgvs
- 		Min/max copy count range not supported
- 		No hgvs or location info
- 		Remaining valid hgvs alleles

vrs_xform_plan combos
- 		{"type":"Allele","policy":"Canonical SPDI"}
- 		{"type":"Allele","policy":"Remaining valid hgvs alleles"}
- 		{"type":"CopyNumberChange","policy":"Copy number change (cn loss|del and cn gain|dup)"}
- 		{"type":"CopyNumberCount","policy":"Absolute copy count"}
- 		{"type":"Unsupported","policy":"Genotype/Haplotype"}
- 		{"type":"Unsupported","policy":"Invalid/unsupported hgvs"}
- 		{"type":"Unsupported","policy":"Min/max copy count range not supported"}
- 		{"type":"Unsupported","policy":"No hgvs or location info"}

```
